# Generated by Django 5.1.6 on 2025-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('envelope', 'Email'), ('codepen', 'Codepen')], default='linkedin', max_length=50),
        ),
    ]
