# Generated by Django 5.2.6 on 2026-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_profile_role_alter_profile_image_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
