# Generated by Django 5.2.6 on 2026-02-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Printed Category',
                'verbose_name_plural': 'Printed Categories',
            },
        ),
        migrations.CreateModel(
            name='PrintedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('main_image', models.ImageField(upload_to='printed/main/', verbose_name='Main Image')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price (MAD)')),
                ('video', models.FileField(blank=True, null=True, upload_to='printed/videos/', verbose_name='Product Video (Optional)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='printed.printedcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Printed Product',
                'verbose_name_plural': 'Printed Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintedProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='printed/gallery/', verbose_name='Additional Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='printed.printedproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
