# Generated by Django 5.2.6 on 2026-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedproduct',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='care',
            field=models.CharField(blank=True, max_length=150, verbose_name='Care Instructions'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='delivery_info',
            field=models.CharField(blank=True, default='Delivery available in Morocco', max_length=150, verbose_name='Delivery Info'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='design',
            field=models.CharField(blank=True, max_length=150, verbose_name='Design'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='In Stock'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='lid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lid'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='straw',
            field=models.CharField(blank=True, max_length=100, verbose_name='Straw'),
        ),
        migrations.AddField(
            model_name='printedproduct',
            name='use',
            field=models.CharField(blank=True, max_length=150, verbose_name='Use'),
        ),
    ]
