# Generated by Django 5.1.6 on 2026-02-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
